# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-23 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authordetail',
            old_name='addr',
            new_name='opus',
        ),
        migrations.RemoveField(
            model_name='authordetail',
            name='age',
        ),
    ]
