# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-24 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_remove_authordetail_opus'),
    ]

    operations = [
        migrations.AddField(
            model_name='authordetail',
            name='age',
            field=models.IntegerField(default=2, max_length=8),
            preserve_default=False,
        ),
    ]
