# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-24 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_authordetail_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordetail',
            name='age',
            field=models.IntegerField(default=0, max_length=8),
        ),
    ]
