# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-24 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20191024_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authordetail',
            name='age',
        ),
    ]
