# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-25 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_remove_authordetail_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordetail',
            name='phone',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
